### ISSUE TITLE
can you help me out, thanks.

### ISSUE THREAD

**Issue by liamxg** [nextstrain/nextstrain-walkthrough#1]
augur frequencies \
>   --metadata results/subsampled_metadata.tsv \
>   --tree results/tree.nwk \
>   --method kde \
>   --pivot-interval 1 \
>   --pivot-interval-units weeks \
>   --narrow-bandwidth 0.041 \
>   --proportion-wide 0.0 \
>   --output auspice/ncov_tip-frequencies.json
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/augur/__init__.py", line 65, in run
    return args.__command__.run(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/augur/frequencies.py", line 103, in run
    tip.attr = {"num_date": np.mean(dates[tip.name])}
KeyError: 'MN908947'

An error occurred (see above) that has not been properly handled by Augur.
To report this, please open a new issue including the original command and the error above:
    <https://github.com/nextstrain/augur/issues/new/choose>

**Comment by liamxg** [comment]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/46078579/198466747-874f7753-f6f3-43fb-b7ff-942c4ad9466e.png">

**Comment by liamxg** [comment]
Could you please tell me how can I do to not show the MN908947 Sequence?

**Comment by huddlej** [comment]
Sorry for the delayed response to this issue, @liamxg! Looking into this more, I suspect that sequence appeared in your output because you ran the `augur align` example code in the tutorial instead of the `nextalign` code. I've removed the optional augur align code from the tutorial (see 4417b6a174e4d650468c7ecc5a771c8acf3d4ac9), so you should be able to run the whole tutorial from start to end without seeing this sequence in your analysis.

**Comment by liamxg** [comment]
@huddlej thanks
