### ISSUE TITLE
I do not find the command that filter by date, can you help me out, thanks.

### ISSUE THREAD

**Issue by liamxg** [nextstrain/nextstrain-walkthrough#2]
Filter the data to eliminate low-quality or undesired data based on genome sequence or metadata attributes. In the following command, we filter by date and sequence length. We also force the inclusion of reference records that we will need for rooting the tree later.

**Comment by liamxg** [comment]
@huddlej

**Comment by huddlej** [comment]
Thank you for pointing out this error in the tutorial, @liamxg! I've removed the text mentioning the date filter, since it was not actually used in the tutorial commands. If you want to filter by date, you can use the `--min-date` or `--max-date` arguments for `augur filter`. Running `augur filter -h` will provide you with a complete list of filter options.

**Comment by liamxg** [comment]
@huddlej thanks
