### ISSUE TITLE
Transfer to Nextstrain org

### ISSUE THREAD

**Issue by genehack** [nextstrain/nextstrain-walkthrough#5]

**Comment by genehack** [comment]
@huddlej it looks like only you and Trevor are "owners" in the "blab" organization — gonna assign this ticket to you, either to do the move or give me perms on the repo to do it.

**Comment by huddlej** [comment]
Done! Let me know if you have any issues hacking on this repo now, @genehack.

**Comment by victorlin** [comment]
Some things to follow up on:

- [x] Several @blab members's permissions were retained through the transfer as outside collaborators, and `@nextstrain/core` only has "read" role (I found out because I tried to push a branch and got 403). Update permissions to only `@nextstrain/core` with "maintain" role.
- [x] Update links in README to use https://github.com/nextstrain/veme-2022 instead of the auto-redirecting https://github.com/blab/veme-2022
